### ISSUE TITLE
Determine why decimals for USDT are not set properly on the Bridge

### ISSUE THREAD

**Issue by lebraat** [publicgoodsnetwork/pgn-monorepo#11]
Carl looking into why bridge is not returning the correct decimal count for USDT - as a result, cannot bridge USDT

**Comment by carlbarrdahl** [comment]
> Carl looking into why bridge is not returning the correct decimal count for USDT - as a result, cannot bridge USDT

Where are you testing this? It works on my side here:
https://pgn-bridge-mainnet-git-usdt-token-public-goods-network.vercel.app/

![image](https://github.com/publicgoodsnetwork/pgn-monorepo/assets/2961337/10fa8a17-cadb-4783-9097-aaff64b80340)
